version: '3.8'

services:
  backend:
    build: ./
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./:/usr/src/backend/
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    networks:
      - eviler-network
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./front

    ports:
      - "3000:3000"
    networks:
      - eviler-network
    depends_on:
      - backend

  db:
    image: postgres:16.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eviler-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

volumes:
  postgres-data:


networks:
  eviler-network:
    external: true