# Generated by Django 4.2.7 on 2023-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_evileruser_managers_evileruser_discord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evileruser',
            old_name='Discord',
            new_name='discord',
        ),
        migrations.AlterField(
            model_name='evileruser',
            name='discord_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
