# Generated by Django 4.2.7 on 2023-12-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_licensekey_remove_update_article_activesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evileruser',
            name='licenseKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.licensekey'),
        ),
        migrations.DeleteModel(
            name='ActiveModule',
        ),
    ]
