# Generated by Django 4.2.7 on 2023-12-01 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_activemodule_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article', models.CharField(default='article', max_length=100)),
                ('Text', models.TextField(default='text')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('Images', models.ManyToManyField(to='api.imagemodel')),
            ],
        ),
    ]
