# Generated by Django 4.2.7 on 2023-12-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_imagemodel_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='image',
            new_name='Image',
        ),
    ]
