# Generated by Django 4.2.11 on 2024-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_evileruser_licensekey_delete_activemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='evileruser',
            name='public_key',
            field=models.CharField(default='', max_length=44),
        ),
        migrations.AlterField(
            model_name='evileruser',
            name='discord',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evileruser',
            name='discord_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
