# Generated by Django 4.2.11 on 2024-03-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_evileruser_public_key_alter_evileruser_discord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evileruser',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='evileruser',
            name='discord_id',
        ),
        migrations.AlterField(
            model_name='evileruser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
