# Generated by Django 4.2.11 on 2024-03-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_evileruser_discord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evileruser',
            name='public_key',
            field=models.CharField(default='', max_length=44, unique=True),
        ),
    ]
