# Generated by Django 5.0.3 on 2024-03-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_evileruser_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evileruser',
            name='password',
            field=models.CharField(null=True),
        ),
    ]
