# Generated by Django 4.2.11 on 2024-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_evileruser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Images',
            field=models.ManyToManyField(null=True, to='api.imagemodel'),
        ),
    ]
