# Generated by Django 4.2.11 on 2024-03-26 17:18

from django.db import migrations, models
import uuid


def generate_uuid(apps, schema_editor):
    ActiveSession = apps.get_model('api', 'ActiveSession')
    for session in ActiveSession.objects.all():
        session.new_id = uuid.uuid4()
        session.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_news_images'),
    ]

    operations = [

        migrations.RenameField(
            model_name='evileruser',
            old_name='licenseKey',
            new_name='license_key',
        ),
        migrations.AddField(
            model_name='activesession',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(generate_uuid),
        migrations.RemoveField(
            model_name='activesession',
            name='id',
        ),
        migrations.RenameField(
            model_name='activesession',
            old_name='new_id',
            new_name='id',
        ),
    ]
