# Generated by Django 4.2.11 on 2024-04-16 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_evileruser_license_key_licensekey_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='nftAddress',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(default=uuid.UUID('e7e1cbd0-0891-44c2-bc61-82869193930e'), max_length=64, unique=True),
        ),
    ]
