# Generated by Django 4.2.11 on 2024-05-10 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_licensekey_nftaddress_alter_licensekey_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Images',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='related_news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.news'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(default=uuid.UUID('7403a8a2-a2e2-4e02-8a4d-d87507af78fb'), max_length=64, unique=True),
        ),
    ]
