# Generated by Django 4.2.11 on 2024-05-10 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_news_images_imagemodel_related_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='related_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.news'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(default=uuid.UUID('53340bd4-fd4d-426e-ac13-0a4d62057803'), max_length=64, unique=True),
        ),
    ]
