# Generated by Django 4.2.11 on 2024-05-10 18:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_imagemodel_related_news_alter_licensekey_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='related_news',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(default=uuid.UUID('4d11b33e-3cba-4229-97b4-af1db4aff6e8'), max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='renewalExpiration',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
