# Generated by Django 4.2.11 on 2024-05-10 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_imagemodel_related_news_delete_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
