# Generated by Django 4.2.11 on 2024-05-10 18:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_licensekey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('904683c1-a262-4d17-911d-fbf938b0e080'), unique=True),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='renewalExpiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
