# Generated by Django 4.2.11 on 2024-05-12 11:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_licensekey_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e3ee5985-4e08-42b1-b2be-0632a4765310'), unique=True),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='renewalExpiration',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
