# Generated by Django 5.0.6 on 2024-05-15 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_licensekey_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('742f78a0-3e1f-4104-aa16-dd92aeb6c831'), unique=True),
        ),
    ]
